config/routes.rb
Rails.application.routes.draw do
  resources :transfers
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :accounts
  root 'home#index'
  devise_for :users
 #  devise_scope :user do
	#   root to: "devise/sessions#new"
	# end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
 

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :transfers, dependent: :destroy
  ACCOUNT_TYPE = ["saving","current"]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transfer.rb
class Transfer < ApplicationRecord
	belongs_to :account
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :accounts
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all.where(:is_approve => "true")
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @transfer = @account.transfers.build
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create 
    # @account = Account.new(account_params)
    
    @account = current_user.accounts.build(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:title,:first_name,:last_name,:phone_number,:dob,:address,:city,:state,:zip_code,:account_type,:account_pin,:account_type,:is_approve )
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  protected

  def after_sign_in_path_for(resource)
    root_path
  end

  private

  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@accounts = Account.all
  end
end

app/controllers/transfers_controller.rb
class TransfersController < InheritedResources::Base
  before_action :set_transfer, only: [:show, :edit, :update, :destroy]

  # GET /transfers
  # GET /transfers.json
  def index
    @transfers = Transfer.all
  end

  # GET /transfers/1
  # GET /transfers/1.json
  def show
  end

  # GET /transfers/new
  def new
    @transfer = Transfer.new
  end

  # GET /transfers/1/edit
  def edit
  end

  # POST /transfers
  # POST /transfers.json
  def create 
    # @transfer = Transfer.new(transfer_params)
    exit
    @transfer = @account.transfers.build(transfer_params)

    respond_to do |format|
      if @transfer.save
        @transfer.user_id = current_user.id
        format.html { redirect_to @transfer, notice: 'Transfer was successfully created.' }
        format.json { render :show, status: :created, location: @transfer }
      else
        format.html { render :new }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transfers/1
  # PATCH/PUT /transfers/1.json
  def update
    respond_to do |format|
      if @transfer.update(transfer_params)
        format.html { redirect_to @transfer, notice: 'Transfer was successfully updated.' }
        format.json { render :show, status: :ok, location: @transfer }
      else
        format.html { render :edit }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transfers/1
  # DELETE /transfers/1.json
  def destroy
    @transfer.destroy
    respond_to do |format|
      format.html { redirect_to transfers_url, notice: 'Transfer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transfer
      @transfer = Transfer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transfer_params
      params.require(:transfer).permit(:account_number,:account_pin,:amount,:user_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, required: true, autofocus: true  %>
  </div>
  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, required: true %>
  </div>
  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number, required: true %>
  </div>
  <div class="field">
    <%= form.label :dob %>
    <%= form.date_field :dob, as: :date, :start_year => 1910, :end_year => 2010, required: true %>
  </div>
  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, required: true  %>
  </div>
  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, required: true  %>
  </div>
  <div class="field">
    <%= form.label :state %>
    <%= form.text_field  :state, required: true%>
  </div>
  <div class="field">
    <%= form.label :zip_code %>
    <%= form.text_field :zip_code, required: true%>
  </div>
  <div class="field">
    <%= form.label :account_type %>
    <%= form.select(:account_type, Account::ACCOUNT_TYPE, class: "form-control") %>
  </div>
  <div class="field">
    <%= form.label :account_pin %>
    <%= form.text_field :account_pin, required: true %>
  </div>
  <div class="field">
    <%= form.label :verify_pin %>
    <%= form.text_field :account_pin, required: true%>
  </div>
 
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
 

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.first_name %></td>
        <td><%= account.account_number %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>first_name:</strong>
  <%= @account.first_name %>
</p>
<p>
  <strong>last_name:</strong>
  <%= @account.last_name %>
</p>
<p>
  <strong>phone_number:</strong>
  <%= @account.phone_number %>
</p>
<p>
  <strong>date_of_birth:</strong>
  <%= @account.dob %>
</p>
<p>
  <strong>address:</strong>
  <%= @account.address %>
</p>
<p>
  <strong>city:</strong>
  <%= @account.city %>
</p>
<p>
  <strong>state:</strong>
  <%= @account.state %>
</p>
<p>
  <strong>zip_code:</strong>
  <%= @account.zip_code %>
</p>
<p>
  <strong>account_type:</strong>
  <%= @account.account_type %>
</p>
<p>
  <strong>account_pin:</strong>
  <%= @account.account_pin %>
</p>


<h1>Transfers</h1>
<h3><%= link_to 'Transfers', transfers_path %></h3>

app/views/home/index.html.erb
 <% if user_signed_in? %>
	Welcome <%= current_user.email %>
<% end %>

<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<h3><%= link_to 'New Account', new_account_path %></h3>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.first_name %></td>
        <td><%= account.account_number %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AccountApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="user_nav">
      <% if user_signed_in? %>
        Signed in as <%= current_user.email %>. Not you?
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/transfers/_form.html.erb
<%= form_with([@account, @account.transfers.build])  do |form| %>
  <% if transfer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transfer.errors.count, "error") %> prohibited this transfer from being saved:</h2>

      <ul>
      <% transfer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :account_number %>
    <%= form.text_field :account_number, required: true, autofocus: true  %>
  </div>
  <div class="field">
    <%= form.label :account_pin %>
    <%= form.text_field :account_pin, required: true, autofocus: true  %>
  </div>
  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount, required: true, autofocus: true  %>
  </div>
 
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transfers/edit.html.erb
<h1>Editing Transfer</h1>

<%= render 'form', transfer: @transfer %>

<%= link_to 'Show', @transfer %> |
<%= link_to 'Back', transfers_path %>

app/views/transfers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transfers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transfers.each do |transfer| %>
      <tr>
        <td><%= link_to 'Show', transfer %></td>
        <td><%= link_to 'Edit', edit_transfer_path(transfer) %></td>
        <td><%= link_to 'Destroy', transfer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transfer', new_transfer_path %>

app/views/transfers/new.html.erb
<h1>New Transfer</h1>

<%= render 'form', transfer: @transfer %>

<%= link_to 'Back', transfers_path %>

app/views/transfers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_transfer_path(@transfer) %> |
<%= link_to 'Back', transfers_path %>